INSERT INTO DIM_SERIES (
    SRS_TITLE_ID,
    EPSD_TITLE_ID,
    SRS_TITLE_NAME,
    EPSD_TITLE_NAME,
    SEASON_EPISODE,
    IS_CURRENT,
    EFFECTIVE_STARTDATE,
    EFFECTIVE_ENDDATE,
    DI_JOB_ID,
    DI_JOB_DT
)
WITH cte AS (
    SELECT 
        CASE WHEN ste.TCONST IS NULL THEN 'Unknown' ELSE ste.TCONST END AS TCONST,
        CASE WHEN stb.PRIMARYTITLE IS NULL THEN 'Unknown' ELSE stb.PRIMARYTITLE END AS PRIMARYTITLE,
        CASE WHEN ste.PARENTTCONST IS NULL THEN 'Unknown' ELSE ste.PARENTTCONST END AS PARENTTCONST,
        CASE WHEN stb2.PRIMARYTITLE IS NULL THEN 'Unknown' ELSE stb2.PRIMARYTITLE END AS PARENTTITLE,
        CASE WHEN ste.SEASON_EPISODE IS NULL THEN '0' ELSE ste.SEASON_EPISODE END AS SEASON_EPISODE
    FROM STG_TITLE_EPISODE ste 
    LEFT JOIN STG_TITLE_BASICS stb ON ste.TCONST = stb.TCONST
    LEFT JOIN STG_TITLE_BASICS stb2 ON ste.PARENTTCONST = stb2.TCONST
    WHERE stb.titleType IN ('tvEpisode', 'tvSeries', 'tvMiniSeries')
    AND stb2.PRIMARYTITLE IS NOT NULL
    AND stb.PRIMARYTITLE IS NOT NULL
    AND ste.SEASON_EPISODE IS NOT NULL
)
SELECT 
    TCONST AS SRS_TITLE_ID, 
    PARENTTCONST AS EPSD_TITLE_ID, 
    PRIMARYTITLE AS SRS_TITLE_NAME, 
    PARENTTITLE AS EPSD_TITLE_NAME, 
    SEASON_EPISODE,
    TRUE AS IS_CURRENT,  
    CURRENT_DATE() AS EFFECTIVE_STARTDATE,  
    NULL AS EFFECTIVE_ENDDATE,  
    'DI_JOB_ID' AS DI_JOB_ID,  
    CURRENT_DATE() AS DI_JOB_DT  
FROM cte;


